services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    restart:
      always
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 10
    ports:
      - "27017:27017"
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "130MB"
  nginx:
    image: nginx:alpine
    ports:
      - "9999:80"
    depends_on:
      - api-payment-1
      - api-payment-2
    networks:
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    command: "nginx -c /etc/nginx/nginx.conf -g 'daemon off;'"
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "50MB"

  api-payment-1:
    image: docker.io/maxsonferovante/api-payment-processor-threads
    pull_policy: always
    container_name: api-payment-1
    environment:
      MONGODB_URI: mongodb://mongodb:27017/rinha
      PAYMENT_PROCESSOR_DEFAULT_URL: http://payment-processor-default:8080
      PAYMENT_PROCESSOR_FALLBACK_URL: http://payment-processor-fallback:8080
      HEALTHCHECK_LEADER_ENABLED: "true"
      PAYMENT_PROCESSOR_MAX_VIRTUAL_THREADS: 30
      HEALTHCHECK_LEADER_URL: http://api-payment-1:8089/health
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "80MB"

  api-payment-2:
    image: docker.io/maxsonferovante/api-payment-processor-threads
    container_name: api-payment-2
    pull_policy: always
    environment:
      MONGODB_URI: mongodb://mongodb:27017/rinha
      PAYMENT_PROCESSOR_DEFAULT_URL: http://payment-processor-default:8080
      PAYMENT_PROCESSOR_FALLBACK_URL: http://payment-processor-fallback:8080
      HEALTHCHECK_LEADER_ENABLED: "false"
      PAYMENT_PROCESSOR_MAX_VIRTUAL_THREADS: 30
      HEALTHCHECK_LEADER_URL: http://api-payment-1:8089/health
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "90MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true